### ISSUE TITLE
Would be awesome to be able to specify sizes of svg's like grunticon does it.

### ISSUE THREAD

**Issue by baconandscript** [gavro/gulp-iconify#1]
Any chance you'll release an update where it's possible (like with grunticon) to specify width and height for the output like so?

.icon {
background-repeat: no-repeat;
display: inline-block;
}

{{#items}}
.icon-{{slug}} {
    background-image: url('{{{datauri}}}');
    width: {{this.width}};
    height: {{this.height}};
}
{{/items}}

Cheers,
Prakash

**Comment by gavro** [comment]
That sounds like a good enhancement.

So, there should be some sort of chain of possibilities/options:
- option: includeDimensions: true/false (default: false)
- fallback option: defaultHeight: []px (default: 100px?)
- fallback option: defaultWidth: []px (default: auto?)
- if enabled: use SVG height/width, otherwise fallback to default values

But should it also support other units? Pixels is not always what people want (rems/ems?)
And what about using background-size instead of height/width? Should there be a default width/height template option that you can override in your own template?

**Comment by LeroyBekOld** [comment]
Dear Gavro,

Is this enhancement still being added? It would be really nice if the width and height could be set automatically within the mustache template file. This way we can just use something like <i class="{{ icon-name }}"></i> out of the box without specifying each of the dimensions in the CSS/SASS/LESS files individually. 

Regards,
Leroy

**Comment by gavro** [comment]
Okay, working on it; will be using grunt-icon logic (from img-stats.js) for this.

**Comment by LeroyBekOld** [comment]
Awesome! Thanks
